# Generated by Django 5.2.14 on 2026-05-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('scored', 'Scored'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('branch', models.CharField(default='Main', max_length=100)),
                ('product_code', models.IntegerField(default=0)),
                ('date_approved', models.DateField(blank=True, null=True)),
                ('date_disbursed', models.DateField(blank=True, null=True)),
                ('first_payment_due', models.DateField(blank=True, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('annual_rate_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('term_months', models.IntegerField(default=12)),
                ('payment_frequency', models.CharField(default='Monthly', max_length=20)),
                ('loan_purpose', models.CharField(blank=True, max_length=50)),
                ('client_gender', models.CharField(default='Male', max_length=10)),
                ('client_dob', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(default='Single', max_length=20)),
                ('num_dependents', models.IntegerField(default=0)),
                ('employment_sector', models.CharField(blank=True, max_length=50)),
                ('months_at_employer', models.IntegerField(default=0)),
                ('monthly_income_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('existing_obligations', models.IntegerField(default=0)),
                ('collateral_type', models.CharField(default='None', max_length=30)),
                ('disbursement_channel', models.CharField(default='Bank_Transfer', max_length=30)),
                ('province', models.CharField(default='Harare', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
